version: '3'

services:
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: main
            POSTGRES_PASSWORD: main
            POSTGRES_DB: main
        ports: 
         - 5432:5432
        volumes:
          - ./database-data:/var/lib/postgresql/data
    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080

###> doctrine/doctrine-bundle ###

